Лабораторная работа №9
Programming-Classrooms/practicalworks-DimaMalets pull request #11
Opened 2023-12-25 07:14 UTC by DimaMalets

## Pull Request лабораторной работы №9

### Условие лабраторной работы
6. Задан текстовый файл input.txt. Требуется определить строки этого файла, 
содержащие максимальную по длине подстроку-палиндром. Если таких 
строк несколько, найти первые 10. Результат вывести на консоль в форме, 
удобной для чтения.

### Вопросы по условию

2024-01-06 16:28 UTC, Voio77 requested changes
Читай комменты!

2024-01-06 16:28 UTC, Voio77 commented on laboratory-task-9/func(1).cpp
> +	return "";
неявное преобразование, которое ты не учитываешь. Переделай!

2024-01-06 16:28 UTC, Voio77 commented on laboratory-task-9/func(1).cpp
> +	return "";
относится ИМЕННО К RETURN

2024-06-17 16:19 UTC, AlexandrOsiptsov approved these changes
Финальный авто-апрув

2024-06-17 16:26 UTC, merged