Лабораторная работа №4
Programming-Classrooms/practicalworks-DimaMalets pull request #4
Opened 2023-11-30 17:31 UTC by DimaMalets

## Pull Request лабораторной работы №4

### Условие лабраторной работы
Вариант 6
В целочисленной прямоугольной матрице найти:
- сумму элементов в тех строках, которые не содержат нулей;
- переставить местами 1-ый и последний столбец, 2-ой и предпоследний и т. д.

### Вопросы по условию

2023-12-10 18:50 UTC, AnnaSatolina requested changes
Есть над чем работать , Дима. Клин код...

2023-12-10 18:50 UTC, AnnaSatolina commented on laboratory-task-4/lab4.cpp
> +//- переставить местами 1-ый и последний столбец, 2-ой и предпоследний и т. д.
Условие должно было быть выше (оно там есть), здесь не надо было ))

2023-12-10 18:50 UTC, AnnaSatolina commented on laboratory-task-4/lab4.cpp
> +void enterSize(size_t& size_i, size_t& size_j) {
тип size_t - беззнаковый тип.

2023-12-10 18:50 UTC, AnnaSatolina commented on laboratory-task-4/lab4.cpp
> +	std::cout << "Enter the number of rows and columns " << '\n';
не вижу смысла писать символ конца строки отдельно. Можно было его сразу в строку дописать.

2023-12-10 18:50 UTC, AnnaSatolina commented on laboratory-task-4/lab4.cpp
> +		for (size_t j  = 0; j < size_j / 2; ++j) {
Вычисления в цикле - это плохо. Нужно перед циклом 1 раз вычислить size_j/2

2023-12-10 18:50 UTC, AnnaSatolina commented on laboratory-task-4/lab4.cpp
> +			std::cout << std::setw(3) << matrix[i][j] << " ";
для чего в конце пробел, если есть ширина поля?

2023-12-10 18:50 UTC, AnnaSatolina commented on laboratory-task-4/lab4.cpp
> +	size_t size_i = 0, size_j = 0;
Лучше писать по одному объявлению в каждой строке

2023-12-10 18:50 UTC, AnnaSatolina commented on laboratory-task-4/lab4.cpp
> +	clearingMemory(matrix, size_i);
а где return 0?

2023-12-24 11:48 UTC, AlexandrOsiptsov requested changes
Названия - беда

2023-12-24 11:48 UTC, AlexandrOsiptsov commented on laboratory-task-4/lab4.cpp
> +void enterSize(int16_t& size_i, int16_t& size_j)
size чего?

2023-12-24 11:48 UTC, AlexandrOsiptsov commented on laboratory-task-4/lab4.cpp
> + }
Ахахах, ну я зарофлил тогда

2023-12-24 11:48 UTC, AlexandrOsiptsov commented on laboratory-task-4/lab4.cpp
> +void newMemory(int32_t**& matrix, int16_t size_i, int16_t size_j)
new memory для чего? + действие не описано

2023-12-24 11:48 UTC, AlexandrOsiptsov commented on laboratory-task-4/lab4.cpp
> +void random(int32_t** matrix, int16_t size_i, int16_t size_j)
random ???

2023-12-24 11:48 UTC, AlexandrOsiptsov commented on laboratory-task-4/lab4.cpp
> +void inputElements(int32_t** matrix, int16_t size_i, int16_t size_j)
Куда? Чьи?

2023-12-24 11:48 UTC, AlexandrOsiptsov commented on laboratory-task-4/lab4.cpp
> +void selctionInput(int32_t** matrix, int16_t size_i, int16_t size_j)
Что? Куда?

2023-12-24 11:48 UTC, AlexandrOsiptsov commented on laboratory-task-4/lab4.cpp
> +void sumElementsStr(int32_t** matrix, int16_t size_i, int16_t size_j) {
Вообще неясно, что задумывается в функции

2023-12-24 11:48 UTC, AlexandrOsiptsov commented on laboratory-task-4/lab4.cpp
> +void outputMatrix(int32_t** matrix, int16_t size_i, int16_t size_j)
Лучше print

2023-12-24 11:48 UTC, AlexandrOsiptsov commented on laboratory-task-4/lab4.cpp
> +void clearingMemory(int32_t**& matrix, int16_t size_i)
ing лучше не использовать в названиях

2023-12-24 11:48 UTC, AlexandrOsiptsov commented on laboratory-task-4/lab4.cpp
> +}
Что с отступами

2023-12-27 07:39 UTC, AlexandrOsiptsov requested changes
Всё менять

2024-06-17 16:19 UTC, AlexandrOsiptsov approved these changes
Финальный авто-апрув

2024-06-17 16:26 UTC, AlexandrOsiptsov approved these changes
Финальный авто-апрув

2024-06-17 16:40 UTC, merged