Лабораторная работа №5
Programming-Classrooms/practicalworks-DimaMalets pull request #6
Opened 2023-12-09 15:02 UTC by DimaMalets

## Pull Request лабораторной работы №5

### Условие лабраторной работы

Вариант 6

### Вопросы по условию

2023-12-10 14:02 UTC, Voio77 requested changes
читай коменты, + добавь отступы, где необходимо. Ну, а так  у меня претензий нет.
Работаем братья и сестра!

2023-12-10 14:28 UTC, AlexandrOsiptsov requested changes
Названия.

2023-12-10 14:28 UTC, AlexandrOsiptsov commented on laboratory-task-5/Header.h
> +double f3(double x);
Отступы просто покинули чат

2023-12-10 14:28 UTC, AlexandrOsiptsov commented on laboratory-task-5/funct.cpp
> +}
Лучше сделать более универсальную функцию. Например, которая запрашивает у пользователя значение и проверяет его на соответствие переданному интервалу, или другим критериям. Писать функцию, которая нужна только для того, чтобы вводить только это значение - плохая практика

2023-12-10 14:28 UTC, AlexandrOsiptsov commented on laboratory-task-5/funct.cpp
> +	std::cin >> a;
`a` и `b` сидели на трубе. Нормальными именами переменные называй. Согласен с Кириллом

2023-12-10 14:28 UTC, AlexandrOsiptsov commented on laboratory-task-5/funct.cpp
> +double theFormAvgRec(double eps, double a, double b, double (*f)(double), uint64_t & n ) {
Читай выше про a и b

2023-12-10 14:28 UTC, AlexandrOsiptsov commented on laboratory-task-5/funct.cpp
> +double theFormSimpson(double eps, double a, double b, double(*f)(double), uint64_t& n) {
Та же история

2023-12-10 14:28 UTC, AlexandrOsiptsov commented on laboratory-task-5/funct.cpp
> +void valueIntegralSimpson(double eps, double a, double b, uint64_t n) {
Та же история

2023-12-10 14:28 UTC, AlexandrOsiptsov commented on laboratory-task-5/funct.cpp
> +}
В конце файла принято оставлять пустую строку

2023-12-10 14:28 UTC, AlexandrOsiptsov commented on laboratory-task-5/main.cpp
> +	double eps, a, b;
а и b

2024-01-06 19:39 UTC, AlexandrOsiptsov requested changes
Исправь помеченные моменты здесь и во всех остальных лабах. Если не понимаешь зачем, можем просто закрыть

2024-01-06 19:39 UTC, AlexandrOsiptsov commented on laboratory-task-5/Header.hpp
> +#endif  //Header.hpp
Пустая строка в конце файла

2024-01-06 19:39 UTC, AlexandrOsiptsov commented on laboratory-task-5/funct.cpp
> +}
Про подобную рекурсию я тебе уже раз 10 говорил

2024-01-06 19:39 UTC, AlexandrOsiptsov commented on laboratory-task-5/funct.cpp
> +}
Что по логическому разделению

2024-01-06 19:39 UTC, AlexandrOsiptsov commented on laboratory-task-5/funct.cpp
> + }
Отступов нет, логического разделения тоже. Глазу воспринимается как сплошной забор строк. Нет вообще никакого желания читать и разбираться что здесь происходит

2024-01-06 19:39 UTC, AlexandrOsiptsov commented on laboratory-task-5/funct.cpp
> +
Пустая строка

2024-01-06 19:39 UTC, AlexandrOsiptsov commented on laboratory-task-5/funct.cpp
> +}
- Почему `int16_t op` на одной строке с `{`?
- Можно было логически разделить код перед `switch`

2024-01-06 19:39 UTC, AlexandrOsiptsov commented on laboratory-task-5/funct.cpp
> +void choosIntegral(double eps, double lower, double upper, uint64_t numberOfSegments)
Орфографическая ошибка в названии

2024-01-06 19:39 UTC, AlexandrOsiptsov commented on laboratory-task-5/main.cpp
> +}
У главной исполняемой функции отсутствует возвращаемое значение

2024-01-06 19:39 UTC, AlexandrOsiptsov commented on laboratory-task-5/Header.hpp
> +
Две строки договаривались. Таким образом подключение библиотек не сливается с объявлением функций

2024-01-06 19:39 UTC, AlexandrOsiptsov commented on laboratory-task-5/funct.cpp
> +
Две строки

2024-01-06 19:39 UTC, AlexandrOsiptsov commented on laboratory-task-5/funct.cpp
> +
Логическое разделение кода

2024-06-17 16:19 UTC, AlexandrOsiptsov approved these changes
Финальный авто-апрув

2024-06-17 16:19 UTC, merged